### PR TITLE
Inject timestamp formatter in Entry instead of a pattern

### LINKED ISSUE #394: Process stuck in SimpleDateFormat
From the stacktrace I noticed that for almost 1 minute there are processes stuck at this point.
It appears to be doing the Date format.
Probably initializing the object continuously is not performant.

```
"reactor-http-epoll-3" #273 daemon prio=5 os_prio=0 cpu=31569546.14ms elapsed=605242.06s tid=0x00007fcca663a010 nid=0x20fc6 waiting for monitor entry  [0x00007fcae07cd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.ListResourceBundle.loadLookup(java.base@17.0.4.1/ListResourceBundle.java:192)
        - waiting to lock <0x00000007ff606850> (a sun.text.resources.cldr.FormatData)
        at java.util.ListResourceBundle.handleGetObject(java.base@17.0.4.1/ListResourceBundle.java:130)
        at java.util.ResourceBundle.getObject(java.base@17.0.4.1/ResourceBundle.java:555)
        at java.util.ResourceBundle.getObject(java.base@17.0.4.1/ResourceBundle.java:558)
        at java.util.ResourceBundle.getStringArray(java.base@17.0.4.1/ResourceBundle.java:538)
        at java.text.DateFormatSymbols.initializeData(java.base@17.0.4.1/DateFormatSymbols.java:759)
        at java.text.DateFormatSymbols.<init>(java.base@17.0.4.1/DateFormatSymbols.java:151)
        at sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(java.base@17.0.4.1/DateFormatSymbolsProviderImpl.java:85)
        at java.text.DateFormatSymbols.getProviderInstance(java.base@17.0.4.1/DateFormatSymbols.java:370)
        at java.text.DateFormatSymbols.getInstanceRef(java.base@17.0.4.1/DateFormatSymbols.java:360)
        at java.text.SimpleDateFormat.<init>(java.base@17.0.4.1/SimpleDateFormat.java:626)
        at java.text.SimpleDateFormat.<init>(java.base@17.0.4.1/SimpleDateFormat.java:603)
        at org.carapaceproxy.core.RequestsLogger$Entry.<init>(RequestsLogger.java:371)
        at org.carapaceproxy.core.RequestsLogger.logRequest(RequestsLogger.java:221)
        at org.carapaceproxy.core.ProxyRequestsManager.processRequest(ProxyRequestsManager.java:168)
        at org.carapaceproxy.core.Listeners.lambda$bootListener$4(Listeners.java:270)
        at org.carapaceproxy.core.Listeners$$Lambda$1438/0x000000080141bd28.apply(Unknown Source)
        at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:959)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677)
        at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:475)
        at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:570)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at reactor.netty.http.server.AbstractHttpServerMetricsHandler.channelRead(AbstractHttpServerMetricsHandler.java:190)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:214)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.carapaceproxy.core.Listeners$2.channelRead(Listeners.java:249)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@17.0.4.1/Thread.java:833)

   Locked ownable synchronizers:
        - None

```

```
"reactor-http-epoll-10" #285 daemon prio=5 os_prio=0 cpu=31752962.66ms elapsed=605241.99s tid=0x00007fcb0c028e80 nid=0x20fd2 waiting for monitor entry  [0x00007fcadfbc1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.ListResourceBundle.loadLookup(java.base@17.0.4.1/ListResourceBundle.java:192)
        - locked <0x00000007ff606850> (a sun.text.resources.cldr.FormatData)
        at java.util.ListResourceBundle.handleGetObject(java.base@17.0.4.1/ListResourceBundle.java:130)
        at java.util.ResourceBundle.getObject(java.base@17.0.4.1/ResourceBundle.java:555)
        at java.util.ResourceBundle.getObject(java.base@17.0.4.1/ResourceBundle.java:558)
        at java.util.ResourceBundle.getStringArray(java.base@17.0.4.1/ResourceBundle.java:538)
        at java.text.DateFormatSymbols.initializeData(java.base@17.0.4.1/DateFormatSymbols.java:759)
        at java.text.DateFormatSymbols.<init>(java.base@17.0.4.1/DateFormatSymbols.java:151)
        at sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(java.base@17.0.4.1/DateFormatSymbolsProviderImpl.java:85)
        at java.text.DateFormatSymbols.getProviderInstance(java.base@17.0.4.1/DateFormatSymbols.java:370)
        at java.text.DateFormatSymbols.getInstanceRef(java.base@17.0.4.1/DateFormatSymbols.java:360)
        at java.text.SimpleDateFormat.<init>(java.base@17.0.4.1/SimpleDateFormat.java:626)
        at java.text.SimpleDateFormat.<init>(java.base@17.0.4.1/SimpleDateFormat.java:603)
        at org.carapaceproxy.core.RequestsLogger$Entry.<init>(RequestsLogger.java:371)
        at org.carapaceproxy.core.RequestsLogger.logRequest(RequestsLogger.java:221)
        at org.carapaceproxy.core.ProxyRequestsManager.processRequest(ProxyRequestsManager.java:168)
        at org.carapaceproxy.core.Listeners.lambda$bootListener$4(Listeners.java:270)
        at org.carapaceproxy.core.Listeners$$Lambda$1438/0x000000080141bd28.apply(Unknown Source)
        at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:959)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677)
        at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:475)
        at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:570)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at reactor.netty.http.server.AbstractHttpServerMetricsHandler.channelRead(AbstractHttpServerMetricsHandler.java:190)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:214)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.carapaceproxy.core.Listeners$2.channelRead(Listeners.java:249)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@17.0.4.1/Thread.java:833)

   Locked ownable synchronizers:
        - None
```

### PR DESCRIPTION
**Pull request by NiccoMlt**
* cache a `SimpleDateFormatter` in configuration
* inject the formatter instead of the pattern when building `Entries`

Fixes #394

### CODE REVIEW

**Comment by NiccoMlt** [comment]
Please note that `SimpleDateFormat` is not thread-safe, but I thought it shouldn't be an issue there.
If you think it could be, an option could be using `DateTimeFormatter`, but patterns are marginally different and this can become a breaking change.

**Comment by dmercuriali** [comment]
I think we should use  `DateTimeFormatter`, this code is executed by multiple threads since it's called by the handler of the `HttpServer`.
The differences in the patterns are minimal and for edge cases imho.

File: carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java [hunk 1]
```diff
@@ -77,7 +77,10 @@ public class RuntimeServerConfiguration {
     private boolean cacheDisabledForSecureRequestsWithoutPublic = false;
     private String mapperClassname;
     private String accessLogPath = "access.log";
+
     private String accessLogTimestampFormat = "yyyy-MM-dd HH:mm:ss.SSS";
+    private SimpleDateFormat accessLogTimestampFormatter;
```
Comment (dmercuriali) [inline carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java:82]: I think we should use  DateTimeFormatter, this code is executed by multiple threads since it's called by the handler of the HttpServer.
The differences in the patterns are minimal and for edge cases imho.

**Review by dmercuriali — CHANGES_REQUESTED** [review]

**Comment by NiccoMlt** [comment]
Using `DateTimeFormatter` now

File: carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java [hunk 2]
```diff
@@ -77,7 +78,10 @@ public class RuntimeServerConfiguration {
     private boolean cacheDisabledForSecureRequestsWithoutPublic = false;
     private String mapperClassname;
     private String accessLogPath = "access.log";
+
     private String accessLogTimestampFormat = "yyyy-MM-dd HH:mm:ss.SSS";
+    private DateTimeFormatter accessLogTimestampFormatter;
```
Comment (pv3nturi) [inline carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java:83]: Maybe if this is used by requestslogger only, it should be inside RequestsLogger

**Review by pv3nturi — CHANGES_REQUESTED** [review]

File: carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java (hunk 2 above)
Comment (NiccoMlt) [reply carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java:83]: Make sense

File: carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java [hunk 3]
```diff
@@ -27,6 +27,7 @@
 import java.security.NoSuchAlgorithmException;
 import java.sql.Timestamp;
 import java.text.SimpleDateFormat;
+import java.time.format.DateTimeFormatter;
```
Comment (dmercuriali) [inline carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java:30]: remove?

**Review by dmercuriali — CHANGES_REQUESTED** [review]

File: carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java (hunk 3 above)
Comment (NiccoMlt) [reply carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java]: You're right, I reverted modifications to this file, as they weren't useful anymore

**Review by dmercuriali — APPROVED** [review]

**Review by pv3nturi — APPROVED** [review]
