### PR TITLE
fix(server): Use default value of Connection Pool when property is no…

### LINKED ISSUE #491: Connection Pool > Use default value when property is not set
When I create a connection pool via API, passing the following parameters in the JSON, for example:
```
{
    "id": "test-pool",
    "domain": ".*test.*",
    "maxConnectionsPerEndpoint": 10,
    "borrowTimeout": 60000,
    "connectTimeout": 10000,
    "stuckRequestTimeout": 120000,
    "idleTimeout": 60000,
    "maxLifeTime": 100000,
    "enabled": true
}
```
When the pool is created, the result is as follows:

```
connectionpool.3.borrowtimeout=60000
connectionpool.3.connecttimeout=10000
connectionpool.3.disposetimeout=0
connectionpool.3.domain=.*test.*
connectionpool.3.enabled=true
connectionpool.3.id=test-pool
connectionpool.3.idletimeout=60000
connectionpool.3.keepalive=false
connectionpool.3.keepalivecount=0
connectionpool.3.keepaliveidle=0
connectionpool.3.keepaliveinterval=0
connectionpool.3.maxconnectionsperendpoint=10
connectionpool.3.maxlifetime=100000
connectionpool.3.stuckrequesttimeout=120000
```

We can observe that some properties I didn’t specify, such as keepalivecount, are set to 0.
For these properties, we already have default values defined in `RuntimeServerConfiguration.java`. It would be appropriate to use the default values if the user doesn’t specify anything in the JSON.

### PR DESCRIPTION
**Pull request by NiccoMlt**
Follow-up of #473, closes #491

### CODE REVIEW

File: carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java [hunk 1]
```diff
@@ -67,16 +77,16 @@ public static final class ConnectionPoolBean {
...
+        private int borrowTimeout = DEFAULT_BORROW_TIMEOUT;
+        private int connectTimeout = DEFAULT_CONNECT_TIMEOUT;
+        private int stuckRequestTimeout = DEFAULT_STUCK_REQUEST_TIMEOUT;
+        private int idleTimeout = DEFAULT_IDLE_TIMEOUT;
+        private int maxLifeTime = DEFAULT_MAX_LIFETIME;
+        private int disposeTimeout = DEFAULT_DISPOSE_TIMEOUT;
+        private int keepaliveIdle = DEFAULT_KEEPALIVE_IDLE;
+        private int keepaliveInterval = DEFAULT_KEEPALIVE_INTERVAL;
+        private int keepaliveCount = DEFAULT_KEEPALIVE_COUNT;
         private boolean keepAlive;
```
Comment (hamadodene) [inline carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java:90]: @NiccoMlt add also keepAlive=true as default

**Review by hamadodene — CHANGES_REQUESTED** [review]

File: carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java (hunk 1 above)
Comment (NiccoMlt) [reply carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java]: done

**Review by hamadodene — APPROVED** [review]
